[package]
name = "postgres-cursor"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
license = "MIT"

[dependencies]
rand = "0.3"

[dependencies.postgres]
git = "https://github.com/sfackler/rust-postgres"
branch = "master"
# version = "0.14"

[dev-dependencies]
lazy_static = "*"
